
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author satellite
 */
public class form3 extends javax.swing.JFrame {
Connection con;
ResultSet rs;
Statement st;
String db; 
int f=0;

/**
     * Creates new form form3
     */
    public form3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        User = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        Pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("NAME");

        jLabel8.setText("USERNAME");

        jLabel9.setText("PASSWORD");

        jLabel10.setText("EMAIL ID");

        jLabel11.setText("CONTACT");

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });

        jLabel1.setText("check");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("check validity");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1)
                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(User)
                            .addComponent(Id)
                            .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  if(Name.getText().trim().length()==0||Pass.getText().trim().length()==0||User.getText().trim().length()==0||Id.getText().trim().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Fill your complete information");
        }
        else
        {
             if(contact.getText().trim().length()>10||contact.getText().trim().length()<10)
            {
            JOptionPane.showMessageDialog(null,"Enter the correct contact no.");
            }
  

                     
                    
             else
             {
            JOptionPane.showMessageDialog(null,"Your information has been saved");
          //  this.setVisible(false);
            try
            {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");  
             db = "jdbc:odbc:Driver={Microsoft Access Driver (*.mdb)};DBQ=D:\\project1\\MUSIC.mdb;";  
            con = DriverManager.getConnection(db,"","");  
            st = con.createStatement();    
             String a,b,c,e,g;
             a=User.getText();
             b= new String(Pass.getPassword());
            c=Name.getText();
            e=Id.getText();
            g=contact.getText();
               while(f==0)
            {
               
            
            
            String qa="insert into Table2 values('"+a+"','"+b+"')";
            st.executeUpdate(qa);
           
            String qb="insert into UserInfo values('"+c+"','"+a+"','"+b+"','"+e+"','"+g+"')";
            st.executeUpdate(qb);
            
            f=1;
            
               
            }
            
            if(f==1)
            {
                this.setVisible(false);
            }
            con.close();
 
JOptionPane.showMessageDialog(null, "you have been signed up...!!");
}
catch(Exception e)
{

JOptionPane.showMessageDialog(null,e);

}
      
        
        
        
        
     //   try
//{
/*    Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost/musiclib","root","");
            Statement st=con.createStatement();
           String query="insert into user values('"+t1.getText()+"','"+t2.getText()+"','"+t4.getText()+"','"+t5.getText()+"','"+t6.getText()+"')";
             st.executeUpdate(query);
 */           
//}
//catch(Exception e)
//{
//    JOptionPane.showMessageDialog(null, e.toString());
//}
     
             }
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    String email = Id.getText();
    int length = email.length();
        
   // boolean flag1 = false;
    boolean flag2 = false;
    boolean flag3 = false;
    boolean flag4 = false;
    boolean flag5 = false;
    boolean flag6 = false;
    boolean flag7 = false;
    int count = 0;


    //Condition 1 
 /*   if((length>3 && length<20)== true)
        flag1 = true;
    else 
        flag1 = false;
*/
    //Condition 2
        int temp = email.length();
        if(email.contains("@"))
        {
            flag2=true;
            int a=email.indexOf("@");
             for(int i=a;i<temp;i++)
             {
            if(email.charAt(i)=='.')
                {
                flag3=true; 
                count=count+1;
                }
               }   
          if(count<1||count>2)
          {
            flag4=false;
           }
        else
          {
            flag4=true;
            }
        }
        else
        {
        flag2 =false;
        JOptionPane.showMessageDialog(null,"no @ symbol present");
        }


    //Condition 3
    //if(email.matches("[A-Z a-z _]+@.*")) //Unable to get the right RegEx here!
      //  flag5 = true;
  //  else
   //     flag5 = false;

    //Condition4
 //   if(Character.isUpperCase(email.charAt(0))==true)
      //      flag6 = true;
    //else
      //  flag6=false;

    if(flag2==true && flag3==true && flag4==true)
      JOptionPane.showMessageDialog(null,"Valid email id");  
    else{
        //if(flag1==false)
       //  JOptionPane.showMessageDialog(null,"invalid length of email id"); 
        if(flag2==false||flag3==false||flag4==false)
            JOptionPane.showMessageDialog(null," '.' missing ");
       // if(flag5==false)
          //  JOptionPane.showMessageDialog(null,"invalid combination of userrname");
        //if(flag6==false)
       //    JOptionPane.showMessageDialog(null,"invalid case of first letter"); 
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
String a,b;
        a=User.getText();

try
{
   Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");  
    db = "jdbc:odbc:Driver={Microsoft Access Driver (*.mdb)};DBQ=D:\\project1\\MUSIC.mdb;";  
    con = DriverManager.getConnection(db,"","");  
    st = con.createStatement();    
    String query="select * from Table2";
            rs=st.executeQuery(query);
    while(rs.next())
    {
                 if(a.equals(rs.getString(1)))
                {
                 f=1;
                }


    
    }
    
    if(f==1)
    {
    
   JOptionPane.showMessageDialog(null,"user name already exists");
                    
    }
    else
    {
    JOptionPane.showMessageDialog(null,"UserName possible","confirmation", 1);
    }

}
catch(Exception e)
{
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JTextField User;
    private javax.swing.JTextField contact;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
